name: ebisu_dart
version: 2.0.0
description: >-
  Ebisu intelligent quiz scheduling algorithm based on Bayesian statistics and an exponential forgetting curve
homepage: https://github.com/ttencate/ebisu_dart
repository: https://github.com/ttencate/ebisu_dart
issue_tracker: https://github.com/ttencate/ebisu_dart/issues
documentation: https://pub.dev/documentation/ebisu_dart/latest
environment:
  sdk: '>=2.3.0 <3.0.0'
dependencies:
  meta: ^1.1.6
dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.6.0
